package com.rootser.qcruncher.integration.service;

import java.util.List;

import org.springframework.stereotype.Component;

import com.google.common.collect.Lists;
@Component
public class TenQKeywords {
	
	public static final List<String> keywords = Lists.newArrayList("td:matches(Accounts receivable.*net)",
			"td:matches(Marketable securities.*current)",
			"td:matches(Other receivables)",
			"td:matches(Cash and cash equivalents)",
			"td:matches(Deferred financing costs)",
			"td:matches(Interest receivable)",
			"td:matches(Prepaid expenses)",
			"td:matches(Total assets)",
			"td:matches(Total current assets)",
			"td:matches(Property and equipment)",
			"td:matches(Operating expenses)",
			"td:matches(Cost of sales)",
			"td:matches(Selling, general and administrative expenses)",
			"td:matches(Research, development and related expenses)",
			"td:matches(Total operating expenses)",
			"td:matches(Operating income)",
			"td:matches(Interest expense and income)",
			"td:matches(Interest expense)",
			"td:matches(Interest income)",
			"td:matches(Total interest expense)",
			"td:matches(Income before income taxes)",
			"td:matches(Provision for income taxes)",
			"td:matches(Net income including noncontrolling interest)",
			"td:matches(Net income attributable to noncontrolling interest)",
			"td:matches(Net income attributable)",
			"td:matches(weighted.*common shares outstanding.*basic)",
			"td:matches(Earnings per share.*shareholders.*basic)",
			"td:matches(Weighted average.*common shares outstanding.*diluted)",
			"td:matches(Earnings per share attributable to.*common.diluted)",
			"td:matches(Cash dividends.*common.*share)",
			"td:matches(Net income.*interest)",
			"td:matches(Cumulative translation adjustment)",
			"td:matches(Defined benefit pension and postretirement plans adjustment)",
			"td:matches(Debt and equity securities.*unrealized gain.*loss)",
			"td:matches(Cash flow hedging instruments, unrealized gain.*loss)",
			"td:matches(Total other comprehensive income.*loss.*net.*tax)",
			"td:matches(Comprehensive income.*loss.*noncontrolling.*interest)",
			"td:matches(Comprehensive.*income.*loss attributable to noncontrolling interest)",
			"td:matches(Comprehensive income.*loss.*attributable to \\w+$)",
			"td:matches(Finished goods)",
			"td:matches(Work in process)",
			"td:matches(Raw materials and supplies)",
			"td:matches(Total inventories)",
			"td:matches(Other current assets)",
			"td:matches(Total current assets)",
			"td:matches(Marketable securities.*non-current)",
			"td:matches(Investments)",
			"td:matches(Property, plant and equipment)",
			"td:matches(Less: Accumulated depreciation)",
			"td:matches(Property, plant and equipment.*net)",
			"td:matches(Goodwill)",
			"td:matches(Intangible assets.*net)",
			"td:matches(Prepaid pension benefits)",
			"td:matches(Other assets)",
			"td:matches(Total assets)",
			"td:matches(Current liabilities)",
			"td:matches(Short-term borrowings and current portion of long-term debt)",
			"td:matches(Accounts payable)",
			"td:matches(Accrued payroll)",
			"td:matches(Accrued income taxes)",
			"td:matches(Other current liabilities)",
			"td:matches(Total current liabilities)",
			"td:matches(Long-term debt)",
			"td:matches(Pension and postretirement benefits)",
			"td:matches(Other liabilities)",
			"td:matches(Total liabilities)",
			"td:matches(Commitments and contingencies)",
			"td:matches(Common stock par value.*par value.*shares issued)",
			"td:matches(Additional paid-in capital)",
			"td:matches(Retained earnings)",
			"td:matches(Treasury stock.*at cost.*shares at.*shares.*)",
			"td:matches(Accumulated other comprehensive income.*loss)",
			"td:matches(Total.*Company shareholders.*equity)",
			"td:matches(Noncontrolling interest)",
			"td:matches(Total equity)",
			"td:matches(Total liabilities and equity)",
			"td:matches(Earnings)",
			"td:matches(Loss.*share)",
			"td:matches(basic)",
			"td:matches(diluted)",
			"td:matches(earnings)",
			"td:matches(loss)"
			);
}
